# Generated by Django 5.2.1 on 2025-05-12 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_planotreino'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('series', models.IntegerField()),
                ('repeticoes', models.IntegerField()),
                ('carga', models.DecimalField(decimal_places=2, max_digits=5)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.planotreino')),
            ],
        ),
    ]
