# Generated by Django 5.2.1 on 2025-05-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_especialidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personaltrainer',
            name='telefone',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
