# Generated by Django 5.2.1 on 2025-05-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_remove_personaltrainer_horarios_horariodisponivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horariodisponivel',
            name='hora_fim',
        ),
        migrations.RemoveField(
            model_name='horariodisponivel',
            name='hora_inicio',
        ),
        migrations.AddField(
            model_name='horariodisponivel',
            name='horario_fim_manha',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horariodisponivel',
            name='horario_fim_noite',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horariodisponivel',
            name='horario_fim_tarde',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horariodisponivel',
            name='horario_inicio_manha',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horariodisponivel',
            name='horario_inicio_noite',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horariodisponivel',
            name='horario_inicio_tarde',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
