# Generated by Django 5.1.6 on 2025-06-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_remove_horariodisponivel_hora_fim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaltrainer',
            name='especialidades',
        ),
        migrations.AddField(
            model_name='personaltrainer',
            name='especialidades',
            field=models.ManyToManyField(to='usuarios.especialidade'),
        ),
    ]
