# Generated by Django 5.2.1 on 2025-06-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_remove_personaltrainer_especialidades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treino',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
    ]
